menu:
  Home: /
  Archives: /archives
  About: /about

excerpt_link: Read More

addthis:
  enable: false

fancybox: false

google_analytics:
rss:

# SCSS Configuration
node_sass:
  debug: true
  outputStyle: nested
  precision: 5
  sourceComments: false